spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/driver
#    username: sa
#    password: sa
#    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
  application:
    name: driverService
#  cloud:
#    uri: http://config:8888
#    fail-fast: true
#    password: ${CONFIG_SERVICE_PASSWORD}
#    username: user

server:
  port: ${PORT:8761}

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#  server:
#    eviction-interval-timer-in-ms: 50000
#    wait-time-in-ms-when-sync-empty: 5