version: '3.1'

services:
  db-driver:
    image: postgres:11
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data-volume-driver:/var/lib/postgresql/data
#  db-order:
#    image: postgres:11
#    env_file:
#      - .env
#    ports:
#      - 5433:5433
#    volumes:
#      - data-volume-order:/var/lib/postgresql/data
#  db-taxi:
#    image: postgres:11
#    env_file:
#      - .env
#    ports:
#      - 5434:5434
#    volumes:
#      - data-volume-taxi:/var/lib/postgresql/data

volumes:
  data-volume-driver:
#  data-volume-order:
#  data-volume-taxi: