version: '3.1'

services:
  db-driver:
    image: postgres:11
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data-volume-driver:/var/lib/postgresql/data

volumes:
  data-volume-driver: