spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  application:
    name: taxiService
  liquibase:
    change-log: classpath:db/changeLogMain.yaml
#  cloud:
#    uri: http://config:8888
#    fail-fast: true
#    password: ${CONFIG_SERVICE_PASSWORD}
#    username: user
#
#server:
#  port: ${PORT:8762}
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#  server:
#    eviction-interval-timer-in-ms: 50000
#    wait-time-in-ms-when-sync-empty: 5